language: cpp

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.6
            - g++-5

install:
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 100
    - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.6 100
    - clang++ -v
    - cd test/
    - ./download-dependencies.sh

script:
    - make
    - ./test

branches:
    only:
        - travis_test

notifications:
    email:
        on_success: change
        on_failure: always
