language: cpp

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.6
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.6
            - clang-3.7
            - g++-5

before_install:
    - pip install --user codecov
    - sudo apt-get -y install ggcov

install:
    - sudo update-alternatives --install $(which gcov)    gcov    $(which gcov-5)      100
    - sudo update-alternatives --install $(which g++)     g++     $(which g++-5)       100
    - sudo update-alternatives --install $(which clang++) clang++ $(which clang++-3.6) 100

script:
    - cd test/
    - ./download-dependencies.sh
    - make
    - ./test

after_success:
    - cp .build/* .
    - codecov

notifications:
    email:
        on_success: change
        on_failure: always
