language: cpp

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.6
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.6
            - clang-3.7
            - g++-5

install:
    - sudo update-alternatives --install $(which g++)     g++     $(which g++-5)       100
    - sudo update-alternatives --install $(which clang++) clang++ $(which clang++-3.6) 100
    - g++ -v
    - clang++ -v

script:
    - cd test/
    - ./download-dependencies.sh
    - make
    - ./test

notifications:
    email:
        on_success: change
        on_failure: always
